project_id = "bdzszxhhkktqmekmlkpv"

[functions.generate-ad]
verify_jwt = false

[functions.car-research]
verify_jwt = false

[functions.email-assistant]
verify_jwt = false

[functions.car-lookup]
verify_jwt = false

[functions.fetch-emails]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.clean-email-body]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
